//generated by gpt
package errors

import (
	"time"
)

var _ = time.Now

const (
	// ErrorInvalidURL error: InvalidURL
	ErrorInvalidURL = "ErrorInvalidURL"

	// ErrorInvalidURLII error: InvalidURLII
	ErrorInvalidURLII = "ErrorInvalidURLII"
)
