//generated by gpt
package errors2

import (
	"time"
)

var _ = time.Now

const (
	// ErrorInvalidURLL error: InvalidURLL
	ErrorInvalidURLL = "ErrorInvalidURLL"

	// ErrorInvalidURLU error: InvalidURLU
	ErrorInvalidURLU = "ErrorInvalidURLU"
)
